(function(global){
  "use strict";
  function el(tag,cls,txt){var n=document.createElement(tag);if(cls)n.className=cls;if(txt!=null)n.textContent=txt;return n;}
  function decoder(v){var d=document.createElement("div");d.innerHTML=String(v==null?"":v);return(d.textContent||"").replace(/\s+/g," ").trim();}
  function normaliser(v){return decoder(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(le|la|les|l|un|une|des|du|de|di|della|del)\b/g," ").replace(/[^a-z0-9]+/g," ").replace(/\s+/g," ").trim();}
  function clone(v){return JSON.parse(JSON.stringify(v));}
  function empreinte(v){var s=JSON.stringify(v),h=2166136261;for(var i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0).toString(36);}

  function creer(options){
    var modele=global.CarnetPreparationModele,preparations={},vue="dashboard",jourOuvert=null,filtreActif="toutes",scrollDashboard=0,dernierEditeId=null;
    (options.preparations||[]).forEach(function(x){preparations[x.journee_id]=x;});
    function legacy(j){return(options.textesLegacy||[]).find(function(x){return x.journee_id===j.uuid;})||null;}
    function etatPour(j){
      if(j._preparationCarnet)return j._preparationCarnet;
      var l=preparations[j.uuid]||null,p=modele.normaliserPreparation(l,legacy(j));
      p.carnetTerminee=!!(l&&l.carnet_terminee);p.recitSourceHash=l&&l.recit_source_hash||null;
      return j._preparationCarnet={isHydrating:true,preparation:p,faits:modele.normaliserFaits(l&&l.carnet_faits_confirmes),photos:modele.normaliserPhotos(l&&l.carnet_photos_selectionnees),revision:0,revisionSauvee:0,statut:"Modifications enregistrées",erreur:null,timer:null,chaine:Promise.resolve(),avantIA:null,consolide:false,finalisation:null,reessayer:null};
    }
    function photosJour(j){return(options.photosParJournee[j.uuid]||[]).filter(function(p){return p.membre_id===options.utilisateurId;}).slice().sort(function(a,b){return String(a.cree_le||"").localeCompare(String(b.cree_le||""));});}
    function faitCle(f){return f.sourceType+":"+(f.sourceId||normaliser(f.libelle));}

    function groupesActivites(j){
      var groupes=(j.lieux||[]).map(function(l){return{sourceType:"lieu",sourceId:l.id,libelle:decoder(l.nom),ids:[l.id],sous:[]};});
      function trouve(mot){return groupes.find(function(g){return normaliser(g.libelle).indexOf(mot)>=0;});}
      var duomo=trouve("duomo"),piazza=trouve("piazza grande"),ferrari=trouve("museo ferrari maranello"),acetaiaSpec=groupes.find(function(g){return /vecchia dispensa/i.test(g.libelle);});
      groupes=groupes.filter(function(g){
        var n=normaliser(g.libelle),parent=null;
        if(duomo&&g!==duomo&&(/wiligelmo|pescheria/.test(n)))parent=duomo;
        if(acetaiaSpec&&g!==acetaiaSpec&&/acetaia/.test(n)&&/balsamique|traditionnel/.test(n))parent=acetaiaSpec;
        if(parent){parent.ids.push(g.sourceId);parent.sous.push(g.libelle);return false;}return true;
      });
      (j.regarder||[]).forEach(function(o){
        var lib=decoder(o.ou||o.quoi),n=normaliser(lib),parent=groupes.find(function(g){var gn=normaliser(g.libelle);return n===gn||n.indexOf(gn)>=0||gn.indexOf(n)>=0;});
        if(!parent&&duomo&&(/duomo|wiligelmo|pescheria/.test(n)))parent=duomo;
        if(!parent&&piazza&&(/preda ringadora|bonissima/.test(n)))parent=piazza;
        if(!parent&&ferrari&&/ferrari|ecusson/.test(n))parent=ferrari;
        if(parent){parent.ids.push(o.id);if(normaliser(parent.libelle)!==n)parent.sous.push(lib);}
        else groupes.push({sourceType:"observation",sourceId:o.id,libelle:lib,ids:[o.id],sous:[]});
      });
      groupes.forEach(function(g){var vus={};g.sous=g.sous.filter(function(x){var n=normaliser(x);if(!n||vus[n])return false;vus[n]=1;return true;});});
      return groupes;
    }
    function faitCorrespondAuGroupe(f,g){
      if(g.ids.indexOf(f.sourceId)>=0)return true;
      /* Les anciennes préparations peuvent référencer un lieu recréé depuis.
         Le repli reste volontairement strict : même type métier et libellé
         normalisé identique, jamais une similarité floue. */
      return f.sourceType===g.sourceType&&normaliser(f.libelle)===normaliser(g.libelle);
    }
    function consoliderEtat(j,e){
      if(e.consolide)return;var groupes=groupesActivites(j),utilises=[];
      var resultat=[];
      groupes.forEach(function(g){var correspond=e.faits.filter(function(f){return faitCorrespondAuGroupe(f,g);});if(correspond.length){resultat.push({sourceType:g.sourceType,sourceId:g.sourceId,libelle:g.libelle,momentFort:correspond.some(function(f){return f.momentFort;}),ordre:resultat.length});correspond.forEach(function(f){utilises.push(f);});}});
      e.faits.forEach(function(f){if(f.sourceType==="manual"||utilises.indexOf(f)<0){f.ordre=resultat.length;resultat.push(f);}});e.faits=resultat;e.consolide=true;e.isHydrating=false;
    }
    function sourcesRecit(e){return{faits:e.faits.map(function(f){return[f.libelle,!!f.momentFort];}),photos:e.photos.map(function(p){return[p.photoId,p.legendeCarnet];}),notes:e.preparation.notesManuelles};}
    function libelleSauvegarde(e){if(e.erreur)return"Erreur d’enregistrement · Réessayer";if(e.statut==="Modifications enregistrées")return"";return e.statut;}
    function libelleAction(e){return e.preparation.carnetTerminee?"<span>✓ Prête</span>":"<span class=\"carnet-action-long\">Terminer la journée</span><span class=\"carnet-action-court\">Terminer</span>";}
    function actualiserStatut(j,e){if(e.revision>e.revisionSauvee)dernierEditeId=j.uuid;document.querySelectorAll('[data-save-day="'+j.uuid+'"]').forEach(function(n){var texte=libelleSauvegarde(e);n.textContent=texte;n.hidden=!texte;n.className="carnet-autosave-statut"+(e.erreur?" erreur":e.revision===e.revisionSauvee?" succes":"");});document.querySelectorAll('[data-day-status="'+j.uuid+'"]').forEach(function(n){var statut=statutUX(e);n.textContent=libelleStatut(statut);n.className="carnet-dashboard-statut";});document.querySelectorAll('[data-finish-day="'+j.uuid+'"]').forEach(function(n){if(!e.finalisation){n.innerHTML=libelleAction(e);n.disabled=!!e.preparation.carnetTerminee;n.classList.toggle("prete",!!e.preparation.carnetTerminee);}});}
    function marquer(j,e,source,delai){e.preparation.carnetTerminee=false;e.preparation.carnetStoryValidated=false;e.revision++;e.statut="Enregistrement…";e.erreur=null;e.reessayer=null;if(source&&e.preparation.carnetStorySource==="ai"&&e.preparation.recitSourceHash!==empreinte(sourcesRecit(e)))e.recitObsolete=true;actualiserStatut(j,e);var badge=document.querySelector(".carnet-preparation-jour.ouvert .carnet-preparation-jour-head>span:last-child");if(badge){badge.textContent="Brouillon";badge.className="brouillon";}var champ=document.querySelector(".carnet-preparation-recit"),rb=champ&&champ.closest(".carnet-preparation-bloc");if(rb){var ia=rb.querySelector(".carnet-preparation-actions .carnet-action-primaire"),aide=rb.querySelector(".carnet-preparation-aide"),avertissement=rb.querySelector(".carnet-recit-obsolete");if(ia)ia.disabled=!iaPossible(e);if(aide&&iaPossible(e))aide.remove();if(avertissement&&!e.recitObsolete)avertissement.remove();}if(rb&&e.recitObsolete&&!rb.querySelector(".carnet-recit-obsolete")){var avert=el("p","carnet-recit-obsolete","Le récit actuel ne prend pas encore en compte vos dernières modifications.");rb.insertBefore(avert,rb.children[1]||null);}clearTimeout(e.timer);e.timer=setTimeout(function(){sauvegarder(j,e,e.revision);},delai==null?120:delai);}
    function donneesSauvegarde(j,e){return{revision:e.revision,p:clone(e.preparation),faits:clone(e.faits),photos:clone(e.photos),journeeId:j.uuid};}
    function sauvegarder(j,e,revision){
      var snap=donneesSauvegarde(j,e);snap.revision=revision;clearTimeout(e.timer);
      e.chaine=e.chaine.catch(function(){}).then(async function(){
        try{
          var p=snap.p,ligne={voyage_id:options.voyageId,journee_id:j.uuid,membre_id:options.utilisateurId,preparation_active:true,carnet_story:p.carnetStory||null,carnet_story_source:p.carnetStory?p.carnetStorySource:"empty",carnet_story_validated:!!(p.carnetTerminee&&p.carnetStory),carnet_terminee:!!p.carnetTerminee,recit_source_hash:p.recitSourceHash||null,notes_manuelles:p.notesManuelles||null,temperature_reelle:p.temperatureReelle,temperature_relevee_le:p.temperatureReleveeLe,afficher_programme_prevu:!!p.afficherProgrammePrevu,maj_le:new Date().toISOString()};
          var up=await options.supabase.from("carnet_journees").upsert(ligne,{onConflict:"journee_id,membre_id"}).select("id").single();if(up.error)throw up.error;e.preparation.id=up.data.id;
          var df=await options.supabase.from("carnet_faits_confirmes").delete().eq("carnet_journee_id",up.data.id);if(df.error)throw df.error;
          if(snap.faits.length){var inf=await options.supabase.from("carnet_faits_confirmes").insert(snap.faits.map(function(f,i){return{carnet_journee_id:up.data.id,source_type:f.sourceType,source_id:f.sourceId,libelle:f.libelle,moment_fort:!!f.momentFort,ordre:i};}));if(inf.error)throw inf.error;}
          var dp=await options.supabase.from("carnet_photos_selectionnees").delete().eq("carnet_journee_id",up.data.id);if(dp.error)throw dp.error;
          if(snap.photos.length){var inp=await options.supabase.from("carnet_photos_selectionnees").insert(snap.photos.map(function(s,i){return{carnet_journee_id:up.data.id,photo_id:s.photoId,ordre:i,principale:!!s.principale,focal_x:s.focalX,focal_y:s.focalY,legende_carnet:s.legendeCarnet||null};}));if(inp.error)throw inp.error;}
          e.revisionSauvee=Math.max(e.revisionSauvee,snap.revision);if(e.revision===e.revisionSauvee){e.statut="Modifications enregistrées";e.erreur=null;}actualiserStatut(j,e);
        }catch(err){console.error("Autosauvegarde carnet",err);e.erreur=err;e.statut="Erreur d’enregistrement — Réessayer";actualiserStatut(j,e);}
      });return e.chaine;
    }
    async function forcerSauvegarde(j,e){clearTimeout(e.timer);if(e.revision>e.revisionSauvee)await sauvegarder(j,e,e.revision);await e.chaine;if(e.erreur)throw e.erreur;}

    function rendreFaits(j,e){consoliderEtat(j,e);var bloc=el("section","carnet-preparation-bloc");bloc.appendChild(el("h4",null,"Ce qui a réellement été fait"));bloc.appendChild(el("p","carnet-preparation-aide","Confirmez les lieux et expériences réellement vécus. Les détails sont regroupés avec leur lieu principal."));var liste=el("div","carnet-faits-liste");
      groupesActivites(j).forEach(function(g){var confirme=e.faits.find(function(f){return f.sourceId===g.sourceId||g.ids.indexOf(f.sourceId)>=0;});var ligne=el("div","carnet-activite carnet-activite-interactive"+(confirme?" confirme":""));var lab=el("label","carnet-fait-confirmation"),ch=document.createElement("input");ch.type="checkbox";ch.checked=!!confirme;lab.append(ch,el("span",null,g.libelle));ligne.appendChild(lab);if(g.sous.length){var ul=el("ul","carnet-activite-details");g.sous.forEach(function(x){ul.appendChild(el("li",null,x));});ligne.appendChild(ul);}ligne.addEventListener("click",function(ev){if(ev.target.closest("label"))return;ch.click();});ch.addEventListener("change",function(){if(ch.checked&&!confirme)e.faits.push({sourceType:g.sourceType,sourceId:g.sourceId,libelle:g.libelle,momentFort:false,ordre:e.faits.length});if(!ch.checked&&confirme)e.faits.splice(e.faits.indexOf(confirme),1);e.faits.forEach(function(f,i){f.ordre=i;});marquer(j,e,true,50);rendre(options.panel);});liste.appendChild(ligne);});
      e.faits.filter(function(f){return f.sourceType==="manual";}).forEach(function(f){var l=el("div","carnet-activite confirme"),s=el("span",null,f.libelle),b=el("button","carnet-action-texte","Supprimer");b.type="button";b.onclick=function(){e.faits.splice(e.faits.indexOf(f),1);marquer(j,e,true,50);rendre(options.panel);};l.append(s,b);liste.appendChild(l);});bloc.appendChild(liste);
      if((j.options||[]).length){var det=el("details","carnet-options-activites"),sum=el("summary",null,"Ajouter une activité optionnelle");det.appendChild(sum);(j.options||[]).forEach(function(o){var lib=decoder(o).split(/\s+[—–]\s+|,/)[0],b=el("button","carnet-option-activite",lib);b.type="button";b.onclick=function(){if(!e.faits.some(function(f){return normaliser(f.libelle)===normaliser(lib);}))e.faits.push({sourceType:"manual",sourceId:null,libelle:lib,momentFort:false,ordre:e.faits.length});marquer(j,e,true,50);rendre(options.panel);};det.appendChild(b);});bloc.appendChild(det);}
      var ajout=el("div","carnet-fait-ajout"),input=document.createElement("input"),aj=el("button","carnet-action-secondaire","Ajouter");input.placeholder="Ajouter un lieu ou une expérience vécue";aj.type="button";aj.onclick=function(){var v=decoder(input.value);if(!v)return;e.faits.push({sourceType:"manual",sourceId:null,libelle:v,momentFort:false,ordre:e.faits.length});marquer(j,e,true,50);rendre(options.panel);};ajout.append(input,aj);bloc.appendChild(ajout);return bloc;
    }
    function rendreMoments(j,e){var bloc=el("section","carnet-preparation-bloc carnet-moments"),nombre=e.faits.filter(function(f){return f.momentFort;}).length;var titre=el("div","carnet-bloc-titre");titre.append(el("h4",null,"Moments forts"),el("span","carnet-moments-compteur",nombre+" / 5 sélectionnés"));bloc.appendChild(titre);bloc.appendChild(el("p","carnet-preparation-aide","Vous pouvez sélectionner jusqu’à 5 moments forts."));if(!e.faits.length)bloc.appendChild(el("p","carnet-preparation-aide","Confirmez d’abord une activité pour pouvoir la choisir comme moment fort."));e.faits.forEach(function(f){var l=el("div","carnet-moment-ligne"),s=el("span",null,f.libelle),b=el("button","carnet-etoile"+(f.momentFort?" active":""),f.momentFort?"★":"☆");l.tabIndex=0;l.setAttribute("role","button");l.setAttribute("aria-label",(f.momentFort?"Retirer ":"Ajouter ")+f.libelle+" des moments forts");b.type="button";b.setAttribute("aria-label",f.momentFort?"Retirer des moments forts":"Ajouter aux moments forts");function basculer(){if(!f.momentFort&&e.faits.filter(function(x){return x.momentFort;}).length>=5){window.alert("Vous avez déjà choisi 5 moments forts. Retirez-en un avant d’en ajouter un autre.");return;}f.momentFort=!f.momentFort;marquer(j,e,true,50);rendre(options.panel);}b.onclick=function(){basculer();};l.addEventListener("click",function(ev){if(ev.target.closest("button"))return;basculer();});l.addEventListener("keydown",function(ev){if(ev.key==="Enter"||ev.key===" "){ev.preventDefault();basculer();}});l.append(s,b);bloc.appendChild(l);});return bloc;}

    function cartePhoto(j,e,s){var p=photosJour(j).find(function(x){return x.id===s.photoId;}),c=el("article","carnet-selection-photo selectionnee");if(!p)return c;var img=document.createElement("img");img.alt=s.legendeCarnet||p.legende||"";img.loading="lazy";(options.urlMiniature||options.urlPhoto)(p.storage_path).then(function(u){if(u)img.src=u;});img.style.objectPosition=(s.focalX*100)+"% "+(s.focalY*100)+"%";c.appendChild(img);var pr=el("label","carnet-photo-principale"),ra=document.createElement("input");ra.type="radio";ra.name="principale-"+j.uuid;ra.checked=s.principale;ra.onchange=function(){e.photos.forEach(function(x){x.principale=x===s;});marquer(j,e,true,50);};pr.append(ra,el("span",null,"Photo principale"));c.appendChild(pr);var le=el("label","carnet-photo-legende","Légende"),inp=document.createElement("input");inp.value=s.legendeCarnet;inp.oninput=function(){s.legendeCarnet=inp.value;marquer(j,e,true,700);};le.appendChild(inp);c.appendChild(le);var ord=el("div","carnet-photo-ordre");[["←",-1],["→",1]].forEach(function(a){var b=el("button",null,a[0]),i=e.photos.indexOf(s);b.type="button";b.disabled=i+a[1]<0||i+a[1]>=e.photos.length;b.onclick=function(){var k=e.photos.indexOf(s),aut=e.photos[k+a[1]];e.photos[k+a[1]]=s;e.photos[k]=aut;e.photos.forEach(function(x,n){x.ordre=n;});marquer(j,e,true,50);rendre(options.panel);};ord.appendChild(b);});c.appendChild(ord);var foc=el("details","carnet-photo-focale");foc.appendChild(el("summary",null,"Position du recadrage"));[["Horizontal","focalX"],["Vertical","focalY"]].forEach(function(x){var l=el("label",null,x[0]),r=document.createElement("input");r.type="range";r.min=0;r.max=1;r.step=.05;r.value=s[x[1]];r.oninput=function(){s[x[1]]=Number(r.value);img.style.objectPosition=(s.focalX*100)+"% "+(s.focalY*100)+"%";marquer(j,e,true,300);};l.appendChild(r);foc.appendChild(l);});c.appendChild(foc);return c;}
    function ouvrirGalerie(j,e){
      var declencheur=document.activeElement,draft=clone(e.photos),overlay=el("div","carnet-photo-modal"),dialog=el("section","carnet-photo-dialog"),head=el("header",null),titre=el("h3",null,"Modifier la sélection"),comp=el("strong",null,draft.length+" / 10"),filtre=el("label","carnet-photo-filtre"),fc=document.createElement("input");
      dialog.setAttribute("role","dialog");dialog.setAttribute("aria-modal","true");titre.id="carnet-photo-dialog-title";dialog.setAttribute("aria-labelledby",titre.id);comp.setAttribute("aria-live","polite");fc.type="checkbox";filtre.append(fc,el("span",null,"Afficher uniquement la sélection"));head.append(titre,comp,filtre);dialog.appendChild(head);
      var grid=el("div","carnet-photo-picker");
      function fermer(){document.removeEventListener("keydown",clavier);overlay.remove();if(declencheur&&declencheur.focus)declencheur.focus();}
      function clavier(ev){if(ev.key==="Escape")fermer();}
      function dessiner(){grid.innerHTML="";comp.textContent=draft.length+" / 10";photosJour(j).forEach(function(p){var sel=draft.find(function(x){return x.photoId===p.id;});if(fc.checked&&!sel)return;var b=el("button","carnet-photo-pick"+(sel?" active":"")),img=document.createElement("img");b.type="button";b.setAttribute("aria-pressed",!!sel);b.setAttribute("aria-label",(sel?"Retirer":"Sélectionner")+" la photo "+(p.legende||p.id));img.loading="lazy";img.alt="";(options.urlMiniature||options.urlPhoto)(p.storage_path).then(function(u){if(u)img.src=u;});b.append(img,el("span",null,sel?"✓":""));b.onclick=function(){if(sel)draft.splice(draft.indexOf(sel),1);else{if(draft.length>=10){window.alert("10 photos maximum pour cette journée.");return;}draft.push({photoId:p.id,ordre:draft.length,principale:draft.length===0,focalX:.5,focalY:.5,legendeCarnet:decoder(p.legende)});}if(draft.length&&!draft.some(function(x){return x.principale;}))draft[0].principale=true;draft.forEach(function(x,i){x.ordre=i;});dessiner();};grid.appendChild(b);});}
      fc.onchange=dessiner;dessiner();dialog.appendChild(grid);var actions=el("footer",null),ann=el("button","carnet-action-secondaire","Annuler"),ok=el("button","carnet-action-primaire","Valider la sélection");ann.type=ok.type="button";ann.onclick=fermer;ok.onclick=function(){e.photos=draft;fermer();marquer(j,e,true,50);if(options.preparerVariantes)options.preparerVariantes(draft.map(function(x){return x.photoId;})).catch(function(err){console.warn("Préparation différée des photos :",err);});rendre(options.panel);};actions.append(ann,ok);dialog.appendChild(actions);overlay.appendChild(dialog);document.body.appendChild(overlay);document.addEventListener("keydown",clavier);titre.setAttribute("tabindex","-1");titre.focus();
    }
    function rendrePhotos(j,e){var bloc=el("section","carnet-preparation-bloc");bloc.appendChild(el("h4",null,"Photos du carnet"));bloc.appendChild(el("p","carnet-photos-compteur",photosJour(j).length+" photos dans la journée · "+e.photos.length+" / 10 sélectionnées pour le carnet"));var grid=el("div","carnet-selection-photos");e.photos.forEach(function(s){grid.appendChild(cartePhoto(j,e,s));});bloc.appendChild(grid);var b=el("button","carnet-action-secondaire","Modifier la sélection");b.type="button";b.onclick=function(){ouvrirGalerie(j,e);};bloc.appendChild(b);return bloc;}
    function rendreNotes(j,e){var bloc=el("section","carnet-preparation-bloc");bloc.appendChild(el("h4",null,"Notes pour préparer le récit"));bloc.appendChild(el("p","carnet-preparation-aide","Ajoutez un souvenir, une anecdote, un ressenti ou une précision utile au récit."));var t=document.createElement("textarea");t.className="carnet-preparation-notes";t.rows=4;t.placeholder="Un détail dont vous voulez vous souvenir…";t.value=e.preparation.notesManuelles;t.oninput=function(){e.preparation.notesManuelles=t.value;marquer(j,e,true,700);};bloc.appendChild(t);return bloc;}
    function iaPossible(e){return e.faits.length>0||!!decoder(e.preparation.notesManuelles)||e.photos.some(function(p){return!!decoder(p.legendeCarnet);});}
    function payloadIA(j,e){return{date:j.date||"",titre_itineraire:decoder(j.titre),distance:decoder(j.rail1),duree:decoder(j.rail2),temperature_reelle:e.preparation.temperatureReelle,faits_confirmes:e.faits.map(function(f){return f.libelle;}),moments_forts:e.faits.filter(function(f){return f.momentFort;}).map(function(f){return f.libelle;}),photos_selectionnees:e.photos.filter(function(p){return decoder(p.legendeCarnet);}).map(function(p){return{photo_id:p.photoId,legende:decoder(p.legendeCarnet)};}),notes_personnelles:decoder(e.preparation.notesManuelles)};}
    function rendreRecit(j,e){var bloc=el("section","carnet-preparation-bloc");bloc.appendChild(el("h4",null,"Récit de la journée"));if(e.recitObsolete)bloc.appendChild(el("p","carnet-recit-obsolete","Le récit actuel ne prend pas encore en compte vos dernières modifications."));var t=document.createElement("textarea");t.className="carnet-preparation-recit";t.rows=8;t.placeholder="Racontez ici les souvenirs réellement vécus pendant cette journée…";t.value=e.preparation.carnetStory;t.oninput=function(){e.preparation.carnetStory=t.value;e.preparation.carnetStorySource=t.value?"manual":"empty";e.preparation.recitSourceHash=null;e.recitObsolete=false;marquer(j,e,false,700);};bloc.appendChild(t);var actions=el("div","carnet-preparation-actions"),possible=iaPossible(e),ia=el("button","carnet-action-primaire",e.preparation.carnetStory?"Recomposer avec l’IA":"Composer le récit avec l’IA");ia.type="button";ia.disabled=!possible;if(!possible)bloc.appendChild(el("p","carnet-preparation-aide","Confirmez une activité, ajoutez une note ou légendez une photo pour composer le récit."));ia.onclick=async function(){if(e.preparation.carnetStory&&!window.confirm("La nouvelle proposition remplacera le récit actuel. Vous pourrez annuler cette génération."))return;ia.disabled=true;ia.textContent="Composition…";try{var res=await options.supabase.functions.invoke("generer-texte-ia",{body:payloadIA(j,e)});if(res.error){var msg=res.error.message,ctx=res.error.context;if(ctx&&ctx.clone)try{var d=await ctx.clone().json();if(d.error)msg=d.error;}catch(_x){}throw new Error(msg);}if(!res.data||!res.data.texte)throw new Error("Réponse vide");e.avantIA={texte:e.preparation.carnetStory,source:e.preparation.carnetStorySource,hash:e.preparation.recitSourceHash};e.preparation.carnetStory=res.data.texte;e.preparation.carnetStorySource="ai";e.preparation.recitSourceHash=empreinte(sourcesRecit(e));e.recitObsolete=false;marquer(j,e,false,50);rendre(options.panel);}catch(err){window.alert(err.message||"La composition a échoué.");ia.disabled=false;ia.textContent=e.preparation.carnetStory?"Recomposer avec l’IA":"Composer le récit avec l’IA";}};actions.appendChild(ia);if(e.avantIA){var undo=el("button","carnet-action-secondaire","Annuler la dernière génération");undo.type="button";undo.onclick=function(){e.preparation.carnetStory=e.avantIA.texte;e.preparation.carnetStorySource=e.avantIA.source;e.preparation.recitSourceHash=e.avantIA.hash;e.avantIA=null;e.recitObsolete=false;marquer(j,e,false,50);rendre(options.panel);};actions.appendChild(undo);}bloc.appendChild(actions);return bloc;}

    function terminer(j,e){
      if(e.finalisation)return e.finalisation;
      e.finalisation=(async function(){
        try{
          e.statut="Finalisation…";e.erreur=null;e.reessayer=null;actualiserStatut(j,e);actualiserFinalisation(j,true);
          await forcerSauvegarde(j,e);
          var champs={carnet_terminee:true,carnet_story_validated:!!decoder(e.preparation.carnetStory),maj_le:new Date().toISOString()},resultat;
          if(e.preparation.id)resultat=await options.supabase.from("carnet_journees").update(champs).eq("id",e.preparation.id).eq("membre_id",options.utilisateurId).select("id,carnet_terminee").single();
          else resultat=await options.supabase.from("carnet_journees").upsert({voyage_id:options.voyageId,journee_id:j.uuid,membre_id:options.utilisateurId,preparation_active:true,carnet_terminee:true,carnet_story_validated:false},{onConflict:"journee_id,membre_id"}).select("id,carnet_terminee").single();
          if(resultat.error)throw resultat.error;
          e.preparation.id=resultat.data.id;e.preparation.carnetTerminee=true;e.preparation.carnetStoryValidated=champs.carnet_story_validated;e.statut="Modifications enregistrées";e.erreur=null;actualiserStatut(j,e);
          if(options.preparerVariantes&&e.photos.length){e.preparationPhotos="en_cours";options.preparerVariantes(e.photos.map(function(x){return x.photoId;})).then(function(){e.preparationPhotos="lancee";rendre(options.panel);}).catch(function(err){e.preparationPhotos="erreur";console.warn("Préparation différée des photos :",err);});}
          rendre(options.panel);var idx=options.jours.indexOf(j);if(options.jours[idx+1]){jourOuvert=options.jours[idx+1].uuid;rendre(options.panel);}
        }catch(err){
          console.error("Finalisation carnet",err);e.preparation.carnetTerminee=false;e.preparation.carnetStoryValidated=false;e.erreur=err;e.statut="Erreur d’enregistrement — Réessayer";e.reessayer=function(){return terminer(j,e);};actualiserStatut(j,e);
        }finally{e.finalisation=null;actualiserFinalisation(j,false);}
      })();
      return e.finalisation;
    }
    function actualiserFinalisation(j,active){var e=etatPour(j);document.querySelectorAll('[data-finish-day="'+j.uuid+'"]').forEach(function(n){n.disabled=active||!!e.preparation.carnetTerminee;n.innerHTML=active?"Finalisation…":libelleAction(e);n.setAttribute("aria-label",active?"Finalisation en cours":e.preparation.carnetTerminee?"Journée prête":"Terminer la journée");n.classList.toggle("prete",!active&&!!e.preparation.carnetTerminee);});}
    function preparationSignificative(e){return e.faits.length>0||e.photos.length>0||!!decoder(e.preparation.notesManuelles)||!!decoder(e.preparation.carnetStory);}
    function statutUX(e){if(e.preparation.carnetTerminee)return"prete";return preparationSignificative(e)?"en-cours":"a-preparer";}
    function libelleStatut(statut){return statut==="prete"?"Prête":statut==="en-cours"?"En cours":"À préparer";}
    function dateJour(j){return((j.dow?j.dow+" ":"")+(j.num||"")+" "+(j.mois||"")).trim();}
    function resumeJour(e){var morceaux=[];if(e.photos.length)morceaux.push(e.photos.length+" / 10 photo"+(e.photos.length>1?"s":""));if(decoder(e.preparation.carnetStory))morceaux.push(e.preparation.carnetStorySource==="legacy"?"récit à revoir":"récit rédigé");else if(preparationSignificative(e))morceaux.push("récit à rédiger");var moments=e.faits.filter(function(f){return f.momentFort;}).length;if(moments)morceaux.push(moments+" / 5 moment"+(moments>1?"s":"")+" fort"+(moments>1?"s":""));return morceaux.length?morceaux.join(" · "):"Aucun souvenir préparé";}
    function ouvrirJour(j){scrollDashboard=window.scrollY||0;jourOuvert=j.uuid;vue="journee";rendre(options.panel);window.scrollTo(0,0);}
    function navigationGlobale(){return document.getElementById("day-nav-sticky");}
    function masquerNavigationGlobale(){var nav=navigationGlobale();if(nav){nav.hidden=true;nav.innerHTML="";}}
    function afficherNavigationGlobale(j,e){var nav=navigationGlobale();if(!nav)return;var index=options.jours.indexOf(j);nav.innerHTML="";nav.setAttribute("data-kind",j.cat||"");var gauche=options.jours[index-1],droite=options.jours[index+1];[[gauche,"prev"],[droite,"next"]].forEach(function(x){var cible=x[0],sens=x[1],lib=cible?(cible.dow+" "+cible.num):sens==="prev"?"‹":"›";if(!cible){var vide=el("span","day-nav-sticky-link day-nav-sticky-"+sens,lib);vide.setAttribute("aria-disabled","true");nav.appendChild(vide);return;}var lien=el("a","day-nav-sticky-link day-nav-sticky-"+sens,sens==="prev"?"‹ "+lib:lib+" ›");lien.href="#";lien.onclick=function(ev){ev.preventDefault();forcerSauvegarde(j,e).then(function(){jourOuvert=cible.uuid;rendre(options.panel);window.scrollTo(0,0);});};nav.appendChild(lien);if(sens==="prev")nav.insertBefore(lien,nav.firstChild);});var action=el("button","carnet-context-action","");action.type="button";action.dataset.finishDay=j.uuid;action.setAttribute("aria-label",e.preparation.carnetTerminee?"Journée prête":"Terminer la journée");action.innerHTML=libelleAction(e);action.disabled=!!e.preparation.carnetTerminee;action.classList.toggle("prete",!!e.preparation.carnetTerminee);action.onclick=function(){terminer(j,e);};nav.insertBefore(action,nav.children[1]||null);nav.hidden=false;}
    function retourDashboard(){vue="dashboard";jourOuvert=null;masquerNavigationGlobale();rendre(options.panel);setTimeout(function(){window.scrollTo(0,scrollDashboard);});}
    function jourRecent(){var candidats=options.jours.filter(function(j){return statutUX(etatPour(j))==="en-cours";});if(!candidats.length)return null;if(dernierEditeId){var local=candidats.find(function(j){return j.uuid===dernierEditeId;});if(local)return local;}return candidats.sort(function(a,b){return String((preparations[b.uuid]||{}).maj_le||"").localeCompare(String((preparations[a.uuid]||{}).maj_le||""));})[0];}
    function carteDashboard(j){var e=etatPour(j),statut=statutUX(e),b=el("button","carnet-dashboard-jour statut-"+statut);b.type="button";b.setAttribute("aria-label",dateJour(j)+", "+decoder(j.titre)+", "+libelleStatut(statut));var texte=el("span","carnet-dashboard-jour-texte"),meta=el("span","carnet-dashboard-jour-meta"),statutTexte=statut==="prete"?"✓ Prête":libelleStatut(statut);texte.append(el("span","carnet-dashboard-date",dateJour(j)),el("strong",null,decoder(j.titre)),el("span","carnet-dashboard-resume",resumeJour(e)));var badge=el("span","carnet-dashboard-statut",statutTexte),chevron=el("span","carnet-dashboard-chevron","›");chevron.setAttribute("aria-hidden","true");meta.append(badge,chevron);b.append(texte,meta);b.onclick=function(){ouvrirJour(j);};return b;}
    function lancerGeneration(gen,suivi){return async function(){if(gen.disabled)return;gen.disabled=true;var debut=Date.now(),timer=setInterval(function(){suivi.textContent="Génération du carnet… "+Math.round((Date.now()-debut)/1000)+" s";},1000);suivi.textContent="Chargement des données… 0 s";try{for(var j of options.jours)await forcerSauvegarde(j,etatPour(j));await options.generer(function(message,secondes){suivi.textContent=message+" "+secondes+" s";},debut);suivi.textContent="Carnet généré.";}catch(err){suivi.textContent="La génération a échoué. Vous pouvez relancer.";window.alert(err.messageUtilisateur||err.message||"La génération a échoué.");}finally{clearInterval(timer);gen.disabled=options.jours.filter(function(j){return etatPour(j).preparation.carnetTerminee;}).length===0;}};}
    function rendreDashboard(panel){
      masquerNavigationGlobale();
      var etats={"a-preparer":0,"en-cours":0,"prete":0},photosPretes=0,total=options.jours.length;
      options.jours.forEach(function(j){var e=etatPour(j),statut=statutUX(e);etats[statut]++;if(statut==="prete")photosPretes+=e.photos.length;});
      var intro=el("header","carnet-dashboard-entete");intro.append(el("p","eyebrow","Carnet souvenir"),el("h2",null,"Préparer le carnet"));panel.appendChild(intro);
      var action=el("section","carnet-dashboard-generation"),contenu=el("div","carnet-dashboard-generation-texte"),label=el("p","carnet-dashboard-kicker","Votre carnet prend forme"),info=el("strong",null,etats.prete+" journée"+(etats.prete>1?"s":"")+" prête"+(etats.prete>1?"s":"")+" sur "+total),barre=el("div","carnet-dashboard-barre"),progression=el("span",null),photos=el("p","carnet-dashboard-photos",photosPretes+" photo"+(photosPretes>1?"s":"")+" sélectionnée"+(photosPretes>1?"s":"")),gen=el("button","carnet-bouton-generer",etats.prete?"Générer le carnet · "+etats.prete+" journée"+(etats.prete>1?"s":""):"Générer le carnet"),suivi=el("p","carnet-generation-suivi","");barre.setAttribute("role","progressbar");barre.setAttribute("aria-label","Journées prêtes pour le carnet");barre.setAttribute("aria-valuemin","0");barre.setAttribute("aria-valuemax",String(total));barre.setAttribute("aria-valuenow",String(etats.prete));progression.style.width=(total?etats.prete/total*100:0)+"%";barre.appendChild(progression);contenu.append(label,info,barre,photos);gen.type="button";gen.disabled=etats.prete===0;gen.onclick=lancerGeneration(gen,suivi);action.append(contenu,gen,suivi);if(!etats.prete)action.appendChild(el("p","carnet-dashboard-generation-aide","Terminez au moins une journée pour générer votre carnet."));panel.appendChild(action);
      var filtres=el("nav","carnet-dashboard-filtres");filtres.setAttribute("aria-label","Filtrer les journées");[["a-preparer","À préparer"],["en-cours","En cours"],["prete","Prêtes"],["toutes","Toutes"]].forEach(function(x){var b=el("button",filtreActif===x[0]?"actif":"",x[1]+(x[0]!=="toutes"?" "+etats[x[0]]:""));b.type="button";b.setAttribute("aria-pressed",filtreActif===x[0]);b.onclick=function(){filtreActif=x[0];rendre(panel);};filtres.appendChild(b);});panel.appendChild(filtres);
      var recent=jourRecent();if(recent){var re=etatPour(recent),continuer=el("section","carnet-dashboard-continuer");continuer.append(el("span","carnet-dashboard-kicker","Continuer"),el("strong",null,dateJour(recent)+" · "+decoder(recent.titre)),el("span",null,resumeJour(re)));var cb=el("button","carnet-action-secondaire","Continuer");cb.type="button";cb.onclick=function(){ouvrirJour(recent);};continuer.appendChild(cb);panel.appendChild(continuer);}
      var liste=el("div","carnet-dashboard-liste"),affiches=options.jours.filter(function(j){return filtreActif==="toutes"||statutUX(etatPour(j))===filtreActif;});affiches.forEach(function(j){liste.appendChild(carteDashboard(j));});if(!affiches.length)liste.appendChild(el("p","carnet-dashboard-vide","Aucune journée dans cette catégorie."));panel.appendChild(liste);
    }
    function rendreJour(j){
      var e=etatPour(j);consoliderEtat(j,e);
      var item=el("article","carnet-preparation-jour ouvert carnet-vue-journee"),head=el("header","carnet-journee-entete"),retour=el("button","carnet-action-texte","← Carnet"),badge=el("span","carnet-dashboard-statut",libelleStatut(statutUX(e)));
      retour.type="button";retour.onclick=retourDashboard;badge.dataset.dayStatus=j.uuid;head.append(retour,badge);item.appendChild(head);
      var titre=el("div","carnet-journee-titre"),save=el("button","carnet-autosave-statut",libelleSauvegarde(e));save.type="button";save.hidden=!libelleSauvegarde(e);save.dataset.saveDay=j.uuid;save.setAttribute("aria-live","polite");save.onclick=function(){if(e.erreur){var action=e.reessayer;e.erreur=null;e.statut=action?"Finalisation…":"Enregistrement…";actualiserStatut(j,e);if(action)action();else sauvegarder(j,e,e.revision);}};titre.append(el("p","carnet-dashboard-date",dateJour(j)),el("h2",null,decoder(j.titre)));var details=el("div","carnet-preparation-details");[j.rail1,j.rail2].filter(Boolean).forEach(function(v){details.appendChild(el("span",null,decoder(v)));});titre.append(details,save);item.appendChild(titre);
      afficherNavigationGlobale(j,e);
      var corps=el("div","carnet-preparation-jour-corps"),sections=[rendreFaits(j,e),rendreMoments(j,e),rendrePhotos(j,e),rendreNotes(j,e),rendreRecit(j,e)];sections.forEach(function(section,indexEtape){var numero=el("span","carnet-etape-numero",String(indexEtape+1).padStart(2,"0")+" —"),blocTitre=section.querySelector(":scope > .carnet-bloc-titre"),titre=section.querySelector(":scope > h4");if(blocTitre){blocTitre.classList.add("section-heading");blocTitre.insertBefore(numero,blocTitre.firstChild);}else if(titre){var heading=el("div","section-heading");heading.append(numero,titre);section.insertBefore(heading,section.firstChild);}});var titreNotes=sections[3].querySelector("h4");if(titreNotes)titreNotes.textContent="Notes & souvenirs";corps.append.apply(corps,sections);
      item.appendChild(corps);
      setTimeout(function(){actualiserStatut(j,e);actualiserFinalisation(j,!!e.finalisation);});return item;
    }
    function rendre(panel){options.panel=panel;panel.innerHTML="";if(vue==="journee"){var j=options.jours.find(function(x){return x.uuid===jourOuvert;});if(j)panel.appendChild(rendreJour(j));else{vue="dashboard";rendreDashboard(panel);}}else rendreDashboard(panel);}
    return{rendre:rendre,ouvrir:function(panel){vue="dashboard";rendre(panel);},fermer:function(){jourOuvert=null;vue="dashboard";masquerNavigationGlobale();}};
  }
  global.CarnetPreparationEcran={creer:creer};
})(window);
